version: '3.9'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper-con
    restart: always
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    container_name: kafka-con
    restart: always
    ports:
      - 9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    volumes:
      - 'kafka_data:/bitnami'
    depends_on:
      - zookeeper
  redis:
    image: redis:alpine
    container_name: redis-con
    restart: always
    ports:
      - 6378:6379
  auth-db:
    image: mongo
    container_name: auth-db-con
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - auth-db-vol:/data/db
  qna-db:
    image: postgres:alpine
    container_name: qna-db-con
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qna
    volumes:
      - qna-db-vol:/var/lib/postgresql/data
  tag-db:
    image: mongo
    container_name: tag-db-con
    restart: always
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - tag-db-vol:/data/db

volumes:
  kafka_data:
  auth-db-vol:
  tag-db-vol:
  qna-db-vol:
