apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db-con
          image: mongo:latest
          envFrom:
            - secretRef:
                name: auth-db-secret
          volumeMounts:
            - name: auth-db-data
              mountPath: /data/db
      volumes:
        - name: auth-db-data
          persistentVolumeClaim:
            claimName: auth-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-svc
spec:
  selector:
    app: auth-db
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-db-pv
spec:
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/auth data"
    type: DirectoryOrCreate
