apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api-con
          image: umairsaleem1/stackoverflow-auth-api:1.0
          envFrom:
            - configMapRef:
                name: auth-api-config-v1.0
            - secretRef:
                name: auth-api-secret

---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-svc
spec:
  selector:
    app: auth-api
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api-config-v1.0
data:
  NODE_ENV: development
  REDIS_URI: redis://redis-svc:6379
  REDIS_TTL: "60"
  PORT: "8001"
  KAFKA_CLIENT_ID: auth-service
  KAFKA_NUM_PARTITIONS: "1"
  KAFKA_REPLICATION_FACTOR: "1"
  KAFKA_BROKERS_LIST: kafka-svc:9092

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secret
stringData:
  MONGO_URI: mongodb://admin:password@auth-db-svc:27017
  HASH_SALT_ROUNDS: "10"
  # ACCESS_TOKEN_PRIVATE_KEY: MIIEogIBAAKCAQEA3YIUpaaQqrMke3KCS8PfkU2BQQospfGm2NSYuvqa+1NSkldyMjqAJkkrRiCa/Bk4A3x0nvCkuiLghzEQHESebNMJlcsgHypjtqcsRc1GOgybJLzTC7oeiB2xDenAD6zjyRtal1ZBIEPkyqnEjcc/nlR3wJZ2TQpYr7ecyVBXhFNomdgHu+82gVq4cM9HyXxrBB4bD1oh3VvGSqg76cEvFO+ISattZgravbsEToHRThFw+w3AXa7vNqcWmugAZPrFx+amBS3ZWNZL5QZfA9DyQAgu/oIXz92YV/wnr3cdYRxBV/P09x6+n2oWfaPskT95RXCke29J4IJb76THCNm0MQIDAQABAoIBAHhxSa7Ewfa/T7/8BJMT31WPsg9ea+aTXiiaeK16pJixtr0x5TsgihvHP0tzYTJguA9VNchSiw9W9YUtDViBiy8bFSQo/b9UekGP5sfRlTTtM9KnBY5j1kQm+OXayv77ACSSxhBx6xmTMS1tYB3DUHlT7oV+irbbQFvTV+Iy2FNvT+8I4op5sksIbdXwpofu2xIv282nXdbZKZrfmO8zF6z8NDM8kjp9IcjWrzKW2dojWPY8iYZ8euG0cFXXe2y6Lxsx4qI+R3sYzAMDIQ9+9KFaBXdBCF5jhoERHhZSigIE5kIlRJjNO3jDSmKS0I7J6K6Tl9FksHfxVDXuCPUBMNECgYEA9AlVAClOmAPNy2pyVRgJGW4rCjBss41L8KpfNd/5HLFMSGVMMtujLDkEElHQZCKYnT/dkJeDgWBgYhv880bzrrIIyqNAcQk1RzCyn1X5Rz/DR+/g33lnKPkm4arREGlWcSDtufh6/TsVq8zSopE9LzI3NTjafOp0AIaDFjnExR0CgYEA6F4EZNxlzkeuGFk9pOiKmDt9XTmuWjBfmg56dwOyUAM3McltODvyTvNYFLoIaeiLfYFYv7f9DdRTuNq695e6AfKQlJkhJBxy0yahQ1W1rDD+QcYpZP9QnpftOUN0Ec5LEtarYHy58635X58HVT0TirShnt5CzdVDR7XeaBe7YyUCgYBNpEZx9bJ2tQcdx/E2V55Vg/KXnE6JVdQqbto59td4JISjp+71Y2Hn6P/9oCAQK92ocjBZF4uUdwhTTppNAG75TtVzOzt+ezKDQuAhx6W24HeOBKjkEOkcZSDUvZckhI8nERXxjDf9J3Y+ob0GUfVIdc6Q1VTWV3Wu0R0Vzi1nlQKBgHDOc8OjW6kxE0uux0Zvvhj5iHrhrcsLAN6BeOKeYMqHRRxedS9/qrq5WGF3ju4bftyHFta8M5WrJpnvViUs+5hGcfox/OzTAsuPTWqrCW92uXilAyOM706O4xORs5+RTtDudnR5GK08IHxTb/PpmrsTxgKiVDwo9Giz2i0emFIhAoGAQaPYvDZTqEXF6FLzhxk9uCjpeTY8X8x1//Jr6YqJRJfO1v8vtH7MC48qTA8SsNTHe9VBowu8lsjbqJmslhRrjCLrbuDrkITISwdKcQereNPHlpQyVl7pMleChKuejMlbmSKIen+9gHqRe/s4dxfFa0Gs7amdm6xJXzQbmQqWVPo=
  # ACCESS_TOKEN_PUBLIC_KEY: MIIBCgKCAQEA3YIUpaaQqrMke3KCS8PfkU2BQQospfGm2NSYuvqa+1NSkldyMjqAJkkrRiCa/Bk4A3x0nvCkuiLghzEQHESebNMJlcsgHypjtqcsRc1GOgybJLzTC7oeiB2xDenAD6zjyRtal1ZBIEPkyqnEjcc/nlR3wJZ2TQpYr7ecyVBXhFNomdgHu+82gVq4cM9HyXxrBB4bD1oh3VvGSqg76cEvFO+ISattZgravbsEToHRThFw+w3AXa7vNqcWmugAZPrFx+amBS3ZWNZL5QZfA9DyQAgu/oIXz92YV/wnr3cdYRxBV/P09x6+n2oWfaPskT95RXCke29J4IJb76THCNm0MQIDAQAB
  # REFRESH_TOKEN_PRIVATE_KEY: MIIEpAIBAAKCAQEAtBZJ2QU6Cej9zYbLXHN2quWW19FpkEr1xp5+nuFeM9kSf9sZGWSRuzLGVnUQoaCl5S+Iz9nm8b0GSVfJJPRXA51JVIJv96/AeKmT1DaVPoLDBXERvV9m7E895CNvayRZ2bKxk2LAmWPA4nGpEkEihd9idCSSjbvHPRRBDTjS37Zp6SYRPcNV5J/ciUZAEevTI1v3fdb02a15pltgg2X/MABySYzwjYy8F26lVTbL5xz+fDdcg8EQSlL9YjBue1eKlJl7jBtlekPOPDDwmNrrmshFDZi89FesBA8a2v2M+MnGPtBDEZmlbpEKkXyktdEZigc3AlEcfTv6LNZ1JsTPdwIDAQABAoIBAAIYCD/HuccHuHu9R3wJs6WFCd30h1+wH29xxFMgl7HOolJuP7p12uPsUTYMImdesM8bYGHaTL8ezYXoyWPum1xlZcbfxWGB36EHh7p97/pMFuxnRieHhnDU8wlGCDOctpa7Zykpise9yy5W1/poW3hnAoQLMNEJD+X76E25DWqgdVgRWgyQ+IZt6yNGJK3R8UE43PLaVhHuBoaHyvlocJThHycBOLFi8s4fq+4BaTh8NI67sueqZHb7MxmM+rgMefoK+0dizTwTY8BrdBv3z9cAVAHRbG40wefiZq3B2Yh4dKzZaCi88cGRsFTNcQZamcM6XFvTjWAxwSgzxmPWBlECgYEA3ND+b+EH4BM0NPNCmHCfaGjlRihOTmN+snP6FBcL4tEX1ptDmEy31Eaa7POlwRVKsXyzwcvVEnjgfWSQZZggLnhZxdrxTnp9LvQI7ny9BW1DYZ4+TKB9V8ytscaKT0TKrgok9vpUZVcD8I5tHtHK+d0NDYIcQfKYo1dQX5w5pLsCgYEA0Mf2iotserkVH3VU+PG4O/mViyFdVmoOX4jzRUz4A70TmZ9g9p8FOBXfy/mkHasLEDXaZzHGUgSgKbvAMjNxztVgMId6guIAdwfrW6tC60eq2U6e5AWC8TqjEa14LtA4fpIJsthpXifdF9TGV5jlKSPdaJkY5rie2otMxbbAMnUCgYEAh4BYIh9czcv7BWMhQpoZt+BmkR66rq+vV6KDm0BpMs5MaozsddDeHY0WFMGOvWVraG61f/6syaETYN8NHMq1NM71h8xKt3XCy8VEldRFyca6ynRolm0FfZNEIwtKZEo6dYIUHNqQX39+E2fS3k6u15UmJVvqKy3LLLCvyXv8g3ECgYEAkamxnN/Bg631ysj1y+n5e/6aE0Pn9w5vkL/f2o3ky9bzAc9suyQfZA3+4jT+B6T6RwkLo8vabgbEJ9nSMjQqRwAf6DvdgctkP6fK0V4fhj+uN4be3H/r55ndg8vfeenUQJprIdhTS1nMq3/MEfmeiKF5LC0EbpSIYDmoCpmCZrECgYBRU6+grVMnX4KRAiyXu8SPlOX595qT9IRGH6us0d4JXWykabaGMom4EaWpD7wps+jOC+FHJ455oUCU+ay6keMpu1diqz8azQJfCZRiCb8Zor8Tq2oMHEDyjxtFUJ9fWST8H7O/X5eIvoknKLzLH8DQZDwstEnj8WiPPLElA6iikg==
  # REFRESH_TOKEN_PUBLIC_KEY: MIIBCgKCAQEAtBZJ2QU6Cej9zYbLXHN2quWW19FpkEr1xp5+nuFeM9kSf9sZGWSRuzLGVnUQoaCl5S+Iz9nm8b0GSVfJJPRXA51JVIJv96/AeKmT1DaVPoLDBXERvV9m7E895CNvayRZ2bKxk2LAmWPA4nGpEkEihd9idCSSjbvHPRRBDTjS37Zp6SYRPcNV5J/ciUZAEevTI1v3fdb02a15pltgg2X/MABySYzwjYy8F26lVTbL5xz+fDdcg8EQSlL9YjBue1eKlJl7jBtlekPOPDDwmNrrmshFDZi89FesBA8a2v2M+MnGPtBDEZmlbpEKkXyktdEZigc3AlEcfTv6LNZ1JsTPdwIDAQAB
  ACCESS_TOKEN_EXPIRY: 1m
  REFRESH_TOKEN_EXPIRY: 1y
  ACCESS_TOKEN_COOKIE_EXPIRY: "86400000"
  REFRESH_TOKEN_COOKIE_EXPIRY: "31536000000"
  ACCESS_TOKEN_PRIVATE_KEY: >
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEA3YIUpaaQqrMke3KCS8PfkU2BQQospfGm2NSYuvqa+1NSkldy
    MjqAJkkrRiCa/Bk4A3x0nvCkuiLghzEQHESebNMJlcsgHypjtqcsRc1GOgybJLzT
    C7oeiB2xDenAD6zjyRtal1ZBIEPkyqnEjcc/nlR3wJZ2TQpYr7ecyVBXhFNomdgH
    u+82gVq4cM9HyXxrBB4bD1oh3VvGSqg76cEvFO+ISattZgravbsEToHRThFw+w3A
    Xa7vNqcWmugAZPrFx+amBS3ZWNZL5QZfA9DyQAgu/oIXz92YV/wnr3cdYRxBV/P0
    9x6+n2oWfaPskT95RXCke29J4IJb76THCNm0MQIDAQABAoIBAHhxSa7Ewfa/T7/8
    BJMT31WPsg9ea+aTXiiaeK16pJixtr0x5TsgihvHP0tzYTJguA9VNchSiw9W9YUt
    DViBiy8bFSQo/b9UekGP5sfRlTTtM9KnBY5j1kQm+OXayv77ACSSxhBx6xmTMS1t
    YB3DUHlT7oV+irbbQFvTV+Iy2FNvT+8I4op5sksIbdXwpofu2xIv282nXdbZKZrf
    mO8zF6z8NDM8kjp9IcjWrzKW2dojWPY8iYZ8euG0cFXXe2y6Lxsx4qI+R3sYzAMD
    IQ9+9KFaBXdBCF5jhoERHhZSigIE5kIlRJjNO3jDSmKS0I7J6K6Tl9FksHfxVDXu
    CPUBMNECgYEA9AlVAClOmAPNy2pyVRgJGW4rCjBss41L8KpfNd/5HLFMSGVMMtuj
    LDkEElHQZCKYnT/dkJeDgWBgYhv880bzrrIIyqNAcQk1RzCyn1X5Rz/DR+/g33ln
    KPkm4arREGlWcSDtufh6/TsVq8zSopE9LzI3NTjafOp0AIaDFjnExR0CgYEA6F4E
    ZNxlzkeuGFk9pOiKmDt9XTmuWjBfmg56dwOyUAM3McltODvyTvNYFLoIaeiLfYFY
    v7f9DdRTuNq695e6AfKQlJkhJBxy0yahQ1W1rDD+QcYpZP9QnpftOUN0Ec5LEtar
    YHy58635X58HVT0TirShnt5CzdVDR7XeaBe7YyUCgYBNpEZx9bJ2tQcdx/E2V55V
    g/KXnE6JVdQqbto59td4JISjp+71Y2Hn6P/9oCAQK92ocjBZF4uUdwhTTppNAG75
    TtVzOzt+ezKDQuAhx6W24HeOBKjkEOkcZSDUvZckhI8nERXxjDf9J3Y+ob0GUfVI
    dc6Q1VTWV3Wu0R0Vzi1nlQKBgHDOc8OjW6kxE0uux0Zvvhj5iHrhrcsLAN6BeOKe
    YMqHRRxedS9/qrq5WGF3ju4bftyHFta8M5WrJpnvViUs+5hGcfox/OzTAsuPTWqr
    CW92uXilAyOM706O4xORs5+RTtDudnR5GK08IHxTb/PpmrsTxgKiVDwo9Giz2i0e
    mFIhAoGAQaPYvDZTqEXF6FLzhxk9uCjpeTY8X8x1//Jr6YqJRJfO1v8vtH7MC48q
    TA8SsNTHe9VBowu8lsjbqJmslhRrjCLrbuDrkITISwdKcQereNPHlpQyVl7pMleC
    hKuejMlbmSKIen+9gHqRe/s4dxfFa0Gs7amdm6xJXzQbmQqWVPo=
    -----END RSA PRIVATE KEY-----
  ACCESS_TOKEN_PUBLIC_KEY: >
    -----BEGIN RSA PUBLIC KEY-----
    MIIBCgKCAQEA3YIUpaaQqrMke3KCS8PfkU2BQQospfGm2NSYuvqa+1NSkldyMjqA
    JkkrRiCa/Bk4A3x0nvCkuiLghzEQHESebNMJlcsgHypjtqcsRc1GOgybJLzTC7oe
    iB2xDenAD6zjyRtal1ZBIEPkyqnEjcc/nlR3wJZ2TQpYr7ecyVBXhFNomdgHu+82
    gVq4cM9HyXxrBB4bD1oh3VvGSqg76cEvFO+ISattZgravbsEToHRThFw+w3AXa7v
    NqcWmugAZPrFx+amBS3ZWNZL5QZfA9DyQAgu/oIXz92YV/wnr3cdYRxBV/P09x6+
    n2oWfaPskT95RXCke29J4IJb76THCNm0MQIDAQAB
    -----END RSA PUBLIC KEY-----
  REFRESH_TOKEN_PRIVATE_KEY: >
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAtBZJ2QU6Cej9zYbLXHN2quWW19FpkEr1xp5+nuFeM9kSf9sZ
    GWSRuzLGVnUQoaCl5S+Iz9nm8b0GSVfJJPRXA51JVIJv96/AeKmT1DaVPoLDBXER
    vV9m7E895CNvayRZ2bKxk2LAmWPA4nGpEkEihd9idCSSjbvHPRRBDTjS37Zp6SYR
    PcNV5J/ciUZAEevTI1v3fdb02a15pltgg2X/MABySYzwjYy8F26lVTbL5xz+fDdc
    g8EQSlL9YjBue1eKlJl7jBtlekPOPDDwmNrrmshFDZi89FesBA8a2v2M+MnGPtBD
    EZmlbpEKkXyktdEZigc3AlEcfTv6LNZ1JsTPdwIDAQABAoIBAAIYCD/HuccHuHu9
    R3wJs6WFCd30h1+wH29xxFMgl7HOolJuP7p12uPsUTYMImdesM8bYGHaTL8ezYXo
    yWPum1xlZcbfxWGB36EHh7p97/pMFuxnRieHhnDU8wlGCDOctpa7Zykpise9yy5W
    1/poW3hnAoQLMNEJD+X76E25DWqgdVgRWgyQ+IZt6yNGJK3R8UE43PLaVhHuBoaH
    yvlocJThHycBOLFi8s4fq+4BaTh8NI67sueqZHb7MxmM+rgMefoK+0dizTwTY8Br
    dBv3z9cAVAHRbG40wefiZq3B2Yh4dKzZaCi88cGRsFTNcQZamcM6XFvTjWAxwSgz
    xmPWBlECgYEA3ND+b+EH4BM0NPNCmHCfaGjlRihOTmN+snP6FBcL4tEX1ptDmEy3
    1Eaa7POlwRVKsXyzwcvVEnjgfWSQZZggLnhZxdrxTnp9LvQI7ny9BW1DYZ4+TKB9
    V8ytscaKT0TKrgok9vpUZVcD8I5tHtHK+d0NDYIcQfKYo1dQX5w5pLsCgYEA0Mf2
    iotserkVH3VU+PG4O/mViyFdVmoOX4jzRUz4A70TmZ9g9p8FOBXfy/mkHasLEDXa
    ZzHGUgSgKbvAMjNxztVgMId6guIAdwfrW6tC60eq2U6e5AWC8TqjEa14LtA4fpIJ
    sthpXifdF9TGV5jlKSPdaJkY5rie2otMxbbAMnUCgYEAh4BYIh9czcv7BWMhQpoZ
    t+BmkR66rq+vV6KDm0BpMs5MaozsddDeHY0WFMGOvWVraG61f/6syaETYN8NHMq1
    NM71h8xKt3XCy8VEldRFyca6ynRolm0FfZNEIwtKZEo6dYIUHNqQX39+E2fS3k6u
    15UmJVvqKy3LLLCvyXv8g3ECgYEAkamxnN/Bg631ysj1y+n5e/6aE0Pn9w5vkL/f
    2o3ky9bzAc9suyQfZA3+4jT+B6T6RwkLo8vabgbEJ9nSMjQqRwAf6DvdgctkP6fK
    0V4fhj+uN4be3H/r55ndg8vfeenUQJprIdhTS1nMq3/MEfmeiKF5LC0EbpSIYDmo
    CpmCZrECgYBRU6+grVMnX4KRAiyXu8SPlOX595qT9IRGH6us0d4JXWykabaGMom4
    EaWpD7wps+jOC+FHJ455oUCU+ay6keMpu1diqz8azQJfCZRiCb8Zor8Tq2oMHEDy
    jxtFUJ9fWST8H7O/X5eIvoknKLzLH8DQZDwstEnj8WiPPLElA6iikg==
    -----END RSA PRIVATE KEY-----
  REFRESH_TOKEN_PUBLIC_KEY: >
    -----BEGIN RSA PUBLIC KEY-----
    MIIBCgKCAQEAtBZJ2QU6Cej9zYbLXHN2quWW19FpkEr1xp5+nuFeM9kSf9sZGWSR
    uzLGVnUQoaCl5S+Iz9nm8b0GSVfJJPRXA51JVIJv96/AeKmT1DaVPoLDBXERvV9m
    7E895CNvayRZ2bKxk2LAmWPA4nGpEkEihd9idCSSjbvHPRRBDTjS37Zp6SYRPcNV
    5J/ciUZAEevTI1v3fdb02a15pltgg2X/MABySYzwjYy8F26lVTbL5xz+fDdcg8EQ
    SlL9YjBue1eKlJl7jBtlekPOPDDwmNrrmshFDZi89FesBA8a2v2M+MnGPtBDEZml
    bpEKkXyktdEZigc3AlEcfTv6LNZ1JsTPdwIDAQAB
    -----END RSA PUBLIC KEY-----
