apiVersion: apps/v1
kind: Deployment
metadata:
  name: tag-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tag-api
  template:
    metadata:
      labels:
        app: tag-api
    spec:
      containers:
        - name: tag-api-con
          image: umairsaleem1/stackoverflow-tag-api:1.0
          envFrom:
            - configMapRef:
                name: tag-api-config-v1.0
            - secretRef:
                name: tag-api-secret

---
apiVersion: v1
kind: Service
metadata:
  name: tag-api-svc
spec:
  selector:
    app: tag-api
  ports:
    - name: http
      port: 8003
      targetPort: 8003
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tag-api-config-v1.0
data:
  NODE_ENV: production
  REDIS_URI: redis://redis-svc:6379
  REDIS_TTL: "60"
  PORT: "8003"
  JWKS_URI: http://auth-api-svc:8001/api/auth/v1/jwks.json
  KAFKA_CLIENT_ID: tag-service
  KAFKA_NUM_PARTITIONS: "1"
  KAFKA_REPLICATION_FACTOR: "1"
  KAFKA_BROKERS_LIST: kafka-svc:9092

---
apiVersion: v1
kind: Secret
metadata:
  name: tag-api-secret
stringData:
  MONGO_URI: mongodb://admin:password@tag-db-svc:27017
