name: CD-auth
on:
  push:
    branches:
      - master
    paths:
      - 'apps/node-auth-service/**'
jobs:
  deploy:
    name: Deploy auth api
    runs-on: ubuntu-latest
    steps:
      # - name: Download build artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: auth-build
      - name: Deploy the application
        run: echo "Deploying auth api..."
